name: Sync to Mirror Repositories

on:
  # Run after the monthly and daily workflows complete
  workflow_run:
    workflows: ["Monthly Anitabi Update", "Daily Anime Pilgrimage Update"]
    types:
      - completed
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync-mirrors:
    # Only run if the triggering workflow was successful
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper git operations

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run mirror synchronization
        run: |
          # Check if load balancing repositories are configured
          if [ -n "${{ secrets.LOAD_BALANCE_REPOSITORIES }}" ]; then
            echo "Running with load balancing enabled"

            # Check if folder ranges are configured
            if [ -n "${{ secrets.FOLDER_RANGES }}" ]; then
              echo "Using custom folder ranges"
              python sync_mirrors.py \
                --mirrors ${{ secrets.MIRROR_REPOSITORIES }} \
                --github-token ${{ secrets.MIRROR_TOKEN }} \
                --bark-url ${{ secrets.BARK_URL || 'https://api.day.app/FXxtHPEhbvdzxrgRpBW7E' }} \
                --load-balance \
                --load-balance-repos ${{ secrets.LOAD_BALANCE_REPOSITORIES }} \
                --folder-ranges '${{ secrets.FOLDER_RANGES }}'
            else
              echo "Using default folder ranges"
              python sync_mirrors.py \
                --mirrors ${{ secrets.MIRROR_REPOSITORIES }} \
                --github-token ${{ secrets.MIRROR_TOKEN }} \
                --bark-url ${{ secrets.BARK_URL || 'https://api.day.app/FXxtHPEhbvdzxrgRpBW7E' }} \
                --load-balance \
                --load-balance-repos ${{ secrets.LOAD_BALANCE_REPOSITORIES }}
            fi
          else
            echo "Running without load balancing"
            python sync_mirrors.py \
              --mirrors ${{ secrets.MIRROR_REPOSITORIES }} \
              --github-token ${{ secrets.MIRROR_TOKEN }} \
              --bark-url ${{ secrets.BARK_URL || 'https://api.day.app/FXxtHPEhbvdzxrgRpBW7E' }}
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.MIRROR_TOKEN }}
